---
abstract: 'WWW::Search backend for news searches'
author:
  - 'Martin Thurn <mthurn@cpan.org>'
build_requires:
  Test::More: 0
  WWW::Search: 2.534
  WWW::Search::Test: 2.265
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: WWW::Search::News
name: WWW-Search-News
no_index:
  directory:
    - inc
    - t
requires:
  URI: 0
  perl: 5.005
resources:
  license: http://dev.perl.org/licenses/
version: 1.078
